### ISSUE TITLE
Add argparse logic to main

### ISSUE THREAD

**Issue by huan** [wechaty/cli#3]
We need to support CLI command arguments, as well as the help message.

the [argparse](https://www.npmjs.com/package/argparse) package can help you achieve this goal, please refer to https://github.com/huan/node-facenet/blob/master/bin/facenet-manager.ts and refactor your code to use argparse, then submit a PR for review.

**Comment by chinggg** [comment]
The code in https://github.com/huan/node-facenet/blob/master/bin/facenet-manager.ts is a bit outdated since `argparse` has released v2, which is [different](https://github.com/nodeca/argparse/blob/master/doc/migrate_v1_to_v2.md) from the original version. I am trying to migrated to v2.
@huan Which arguments do you think can be added to the argument parser?
- `name`: the name to create Wechaty bot instance

**Comment by huan** [comment]
Thanks for the PR!

I'd like to suggest that you can make a decision and ask for my comments, but there's no need to wait for my reply.

If I missed any issues/questions, please go ahead by following the best decision you can make.
